"""add otp and verification fields to users

Revision ID: 75b44e64bee8
Revises: 4587e8171895
Create Date: 2026-05-22 13:29:58.153701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b44e64bee8'
down_revision: Union[str, Sequence[str], None] = '4587e8171895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add is_verified with server_default so existing rows get False
    op.add_column('users', sa.Column(
        'is_verified', sa.Boolean(),
        nullable=False,
        server_default='false'
    ))
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
